// Date: 09/10/2014 00:38:38
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package ttftcuts.physis.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSocketTable extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Backboard;
    ModelRenderer FLLeg;
    ModelRenderer FRLeg;
    ModelRenderer BLLeg;
    ModelRenderer BRLeg;
    ModelRenderer FLRim;
    ModelRenderer FRRim;
    ModelRenderer BLRim;
    ModelRenderer BRRim;
  
  public ModelSocketTable()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 6);
      Body.addBox(0F, 0F, 0F, 16, 7, 16);
      Body.setRotationPoint(-8F, 9F, -8F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Backboard = new ModelRenderer(this, 15, 29);
      Backboard.addBox(0F, 0F, 0F, 16, 9, 1);
      Backboard.setRotationPoint(-8F, 0F, 7F);
      Backboard.setTextureSize(128, 64);
      Backboard.mirror = true;
      setRotation(Backboard, 0F, 0F, 0F);
      FLLeg = new ModelRenderer(this, 52, 11);
      FLLeg.addBox(0F, 0F, 0F, 3, 8, 3);
      FLLeg.setRotationPoint(-8F, 16F, -8F);
      FLLeg.setTextureSize(128, 64);
      FLLeg.mirror = true;
      setRotation(FLLeg, 0F, 0F, 0F);
      FRLeg = new ModelRenderer(this, 52, 0);
      FRLeg.addBox(0F, 0F, 0F, 3, 8, 3);
      FRLeg.setRotationPoint(5F, 16F, -8F);
      FRLeg.setTextureSize(128, 64);
      FRLeg.mirror = true;
      setRotation(FRLeg, 0F, 0F, 0F);
      BLLeg = new ModelRenderer(this, 0, 11);
      BLLeg.addBox(0F, 0F, 0F, 3, 8, 3);
      BLLeg.setRotationPoint(-8F, 16F, 5F);
      BLLeg.setTextureSize(128, 64);
      BLLeg.mirror = true;
      setRotation(BLLeg, 0F, 0F, 0F);
      BRLeg = new ModelRenderer(this, 0, 0);
      BRLeg.addBox(0F, 0F, 0F, 3, 8, 3);
      BRLeg.setRotationPoint(5F, 16F, 5F);
      BRLeg.setTextureSize(128, 64);
      BRLeg.mirror = true;
      setRotation(BRLeg, 0F, 0F, 0F);
      FLRim = new ModelRenderer(this, 0, 39);
      FLRim.addBox(0F, 0F, 0F, 1, 1, 15);
      FLRim.setRotationPoint(-8F, 8F, -8F);
      FLRim.setTextureSize(128, 64);
      FLRim.mirror = true;
      setRotation(FLRim, 0F, 0F, 0F);
      FRRim = new ModelRenderer(this, 32, 39);
      FRRim.addBox(0F, 0F, 0F, 1, 1, 15);
      FRRim.setRotationPoint(7F, 8F, -8F);
      FRRim.setTextureSize(128, 64);
      FRRim.mirror = true;
      setRotation(FRRim, 0F, 0F, 0F);
      BLRim = new ModelRenderer(this, 48, 0);
      BLRim.addBox(0F, 0F, 0F, 1, 8, 1);
      BLRim.setRotationPoint(-8F, 0F, 6F);
      BLRim.setTextureSize(128, 64);
      BLRim.mirror = true;
      setRotation(BLRim, 0F, 0F, 0F);
      BRRim = new ModelRenderer(this, 12, 0);
      BRRim.addBox(0F, 0F, 0F, 1, 8, 1);
      BRRim.setRotationPoint(7F, 0F, 6F);
      BRRim.setTextureSize(128, 64);
      BRRim.mirror = true;
      setRotation(BRRim, 0F, 0F, 0F);
  }
  
  //public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  public void render()
  {
    //super.render(entity, f, f1, f2, f3, f4, f5);
    //setRotationAngles(f, f1, f2, f3, f4, f5);
	  float f5 = 1f/16f;
    Body.render(f5);
    Backboard.render(f5);
    FLLeg.render(f5);
    FRLeg.render(f5);
    BLLeg.render(f5);
    BRLeg.render(f5);
    FLRim.render(f5);
    FRRim.render(f5);
    BLRim.render(f5);
    BRRim.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
